# Generated by Django 2.1.3 on 2018-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrpic', models.FileField(blank=True, null=True, upload_to='static/qrpic/', verbose_name='二维码照片')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '二维码表',
                'verbose_name_plural': '二维码表',
                'db_table': 't_exam',
            },
        ),
    ]
