# Generated by Django 2.1.3 on 2018-11-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='qrpic',
            field=models.FileField(blank=True, null=True, upload_to='qrpic/', verbose_name='二维码照片'),
        ),
    ]
