# Generated by Django 2.1.3 on 2018-11-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20181129_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='brightness',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='明亮度'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='contrast',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='对比度'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='newname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='新文件名'),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='remark',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='内容'),
        ),
    ]
