# Generated by Django 2.1.3 on 2018-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20181129_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='brightness',
            field=models.FloatField(blank=True, help_text='范围（1.0~10.0）', max_length=20, null=True, verbose_name='明亮度'),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='contrast',
            field=models.FloatField(blank=True, help_text='范围（1.0~10.0）', max_length=20, null=True, verbose_name='对比度'),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='remark',
            field=models.TextField(blank=True, help_text='不支持中文啊小老弟', max_length=1024, null=True, verbose_name='内容'),
        ),
    ]
