# Generated by Django 2.1.3 on 2018-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20181129_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='qrpic',
            field=models.FileField(blank=True, help_text='仅支持.jpg，.png，.bmp，.gif', null=True, upload_to='qrpic/', verbose_name='二维码照片'),
        ),
    ]
