# Generated by Django 2.1.3 on 2018-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20181129_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='remark',
            field=models.TextField(blank=True, help_text='支持url、英文; 不支持中文啊小老弟', max_length=1024, null=True, verbose_name='内容'),
        ),
    ]
